version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: your_username  # Ensure this is the correct username
      POSTGRES_PASSWORD: your_password  # Ensure this is the correct password
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - mynetwork

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres-db:
